Set search_path to kotikisecurity;

Drop table user_authority;
Drop table friendship;
Drop table cats;
Drop table owners;


    create table if not exists owners
    (
        id         bigint generated by default as identity
            primary key,
        birth_date date,
        name       varchar(255),
        password   varchar(255) not null,
        username   varchar(255) not null
            constraint username_unique
                unique
    );

    create table if not exists user_authority
    (
        user_id bigint not null
            constraint ref_to_owners_table
                references owners,
        roles   varchar(255)
    );

    create table if not exists cats
    (
        id         bigint generated by default as identity
            primary key,
        birth_date date,
        breed      varchar(255),
        color      varchar(255),
        name       varchar(255) not null,
        owner_id   bigint
            constraint ref_to_owners_table
                references owners
    );

    create table if not exists friendship
    (
        cat1_id bigint not null
            constraint ref1_to_cats_table
                references cats,
        cat2_id bigint not null
            constraint ref2_to_cats_table
                references cats
    );
